# Generated by Django 4.2.6 on 2023-11-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('precoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precoDesconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('midia', models.IntegerField(choices=[(0, 'Digital'), (1, 'Fisico')], default=1)),
                ('link', models.CharField(max_length=350)),
                ('linkImagem', models.CharField(blank=True, max_length=500, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.loja')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.plataforma')),
            ],
        ),
    ]
