# Generated by Django 4.2.6 on 2023-10-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
